### ISSUE TITLE
grabCurrentUrl vs grabFromCurrentUrl

### ISSUE THREAD

**Issue by eXorus** [Codeception/module-playwright#2]
In WebDriver it's `grabFromCurrentUrl`
In this module it's `grabCurrentUrl`

Is it expected ?

**Comment by eXorus** [comment]
same for executeScript vs executeJS

**Comment by eXorus** [comment]
same for refreshPage vs reloadPage

**Comment by eXorus** [comment]
same for waitForFunction? vs waitForJS

same for waitForVisible vs waitForElementVisible

**Comment by eXorus** [comment]
seeCurrentUrlMatches doesn't exist.

**Comment by eXorus** [comment]
same for waitForClickable vs waitForElementClickable

**Comment by DavertMik** [comment]
Thanks, adding aliases. Somehow this was not in original test suite

**Comment by DavertMik** [comment]
This one should be fixed by last commit in main branch
Maybe tests also needed to be added

**Comment by DavertMik** [comment]
Fixed and added tests https://github.com/Codeception/module-playwright/actions/runs/10984757588
